# Generated by Django 3.0.5 on 2021-05-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Quiz_App', '0003_auto_20210503_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
