# Generated by Django 3.0.5 on 2021-05-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Quiz_App', '0005_response_responsesendername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
