# Generated by Django 3.0.5 on 2021-05-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Quiz_App', '0006_delete_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
