# Generated by Django 3.0.5 on 2021-05-03 10:34

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Quiz_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Response_User_id', models.IntegerField()),
                ('answer', jsonfield.fields.JSONField(max_length=200)),
                ('Form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Quiz_App.Formtitle')),
                ('Question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Quiz_App.Questions')),
            ],
        ),
    ]
