# Generated by Django 3.0.5 on 2021-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Quiz_App', '0004_auto_20210503_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Responsesendername',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
